# This workflow will send notification about new releases in selected telegram chats
# Read more here https://github.com/v1a0/telegram-notify-workflow

name: Telegram notifications

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - dev
      - 'dev/**'
  pull_request:
    branches:
      - main
      - dev
      - 'dev/**'

jobs:
  telegram-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        
    - name: Clone repo, install requirements
      run: |
        git clone https://github.com/v1a0/telegram-notify-workflow.git ./telegram-notify-workflow
        cd telegram-notify-workflow
        python -m pip install -r requirements.txt
        
    - name: Run bot
      env:
        secrets.TG_API_TOKEN: ${{ secrets.TG_API_TOKEN }}
        secrets.TG_CHAT_IDS: ${{ secrets.TG_CHAT_IDS }}
      run: |
        cd telegram-notify-workflow
        python bot.py
